language: c
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libc6-i386
before_script:
  - chmod +x tools/compile-gamemode.sh
  - chmod +x tools/pawn/pawncc
script: tools/compile-gamemode.sh